server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**, /register, /login, /home, /
        - id: med-center-server
          uri: lb://med-center-server
          predicates:
            - Path=/medcenters/**
        - id: blood-request-server
          uri: lb://blood-request-service
          predicates:
            - Path=/requests/**
        - id: donor-service
          uri: http://localhost:8084
          predicates:
            - Path=/donor/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
