spring:
  application:
    name: donation-history-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_blood_donation
    username: postgres
    password: Qt4076042
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka