spring:
  application:
    name: med-center-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_blood_donation
    username: postgres
    password: 888
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8082

# ДОБАВЬТЕ ЭТИ НАСТРОЙКИ ДЛЯ YANDEX MAPS API
yandex:
  maps:
    api:
      key: "92fb74a1-4389-4f41-8801-8e9d93e4548c"  # Замените на ваш реальный ключ

jwt:
  secret: "mySuperSecureJWTSecretKeyForBloodDonationSystem2024WithMoreThan64CharactersToEnsure512bitSecurity"
  expiration: 86400000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka